Pipeline keyword now includes the sensitivity list. The pipesv/demo/make executable now checks for if ffmpeg and verilator are installed.

diff --git a/demo/make b/demo/make
--- a/demo/make
+++ b/demo/make
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+if ! command -v verilator &> /dev/null; then
+    echo "Error: verilator is not installed or not on PATH."
+    exit 1
+fi
+
+if ! command -v ffmpeg &> /dev/null; then
+    echo "Error: ffmpeg is not installed or not on PATH."
+    exit 1
+fi
+
 rm -f output.vcd
 rm -f output.png
 rm -f image.raw
